version: '3.8'

services:
  backend:
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 80"
    restart: always
    ports:
      - "80:80"
    container_name: saber_backend
